### ISSUE TITLE
Print.h not included in newer platforms

### ISSUE THREAD

**Issue by Aduen** [arduino-libraries/LiquidCrystal#33] opened 2020-05-06 09:40 UTC
Print.h dependency is not included with some boards (for example mbed based boards). Easy fix is to replace Print.h with Arduino.h

**Comment by per1234** [comment] 2020-05-06 10:05
Closing as duplicate of https://github.com/arduino/Arduino/issues/10025, which was fixed by https://github.com/arduino/ArduinoCore-API/commit/7f8de5869ee3de7a915bf1db64313c08595b3ac3.

The problem will be resolved on the next release of the boards platform.

**Closed by per1234** 2020-05-06 10:05 UTC
